# The sysroot for the demo application.


[Python]
version = "3.7.8"

[Python.win]
install_host_from_source = false


[Qt]
version = "5.12.9"
edition = "opensource"
configure_options = ["-opengl", "desktop", "-no-dbus", "-qt-pcre"]
skip = ["qtactiveqt", "qtconnectivity", "qtdoc", "qtgamepad", "qtlocation",
        "qtmultimedia", "qtnetworkauth", "qtquickcontrols", "qtquickcontrols2",
        "qtremoteobjects", "qtscript", "qtscxml", "qtsensors", "qtserialbus",
        "qtserialport", "qtspeech", "qtsvg", "qttools", "qttranslations",
        "qtwayland", "qtwebchannel", "qtwebengine", "qtwebsockets",
        "qtwebview", "qtxmlpatterns"]

[Qt.android]
install_from_source = false
ssl = "openssl-linked"

[Qt.ios]
install_from_source = false
ssl = "securetransport"

[Qt.linux]
ssl = "openssl-runtime"

[Qt.macos]
ssl = "openssl-linked"

[Qt.win]
ssl = "openssl-linked"
static_msvc_runtime = true


[OpenSSL]
enabled_targets = ["android", "linux", "macos", "win"]
version = "1.1.1g"

[OpenSSL.linux]
install_from_source = false


[SIP]
version = "4.19.23"
module_name = "PyQt5.sip"


[zlib]
version = "1.2.11"
install_from_source = false

[zlib.win]
install_from_source = true
static_msvc_runtime = true
